### ISSUE TITLE
Any online docs?

### ISSUE THREAD

**Issue by BANOnotIT** [mnasyrov/ditox#29]
I found your library pretty interesting and interface you designed a great one. But don't you think creating a hosted version of docs would be a great improvement of DX?

**Comment by mnasyrov** [comment]
Thanks, making a website with documentation is a good idea.

**Comment by mnasyrov** [comment]
Introduced the website - https://ditox.js.org

**Comment by BANOnotIT** [comment]
That's great! Many thanks :handshake:
